src/objects/Country_State_Dependency__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds state/country dependency (if any)</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Country State Dependency</label>
</CustomObject>

src/classes/Test_StateCountryController.cls
@isTest
public Class Test_StateCountryController
{
static testmethod void testgetStateCountryValues(){
Country_State_Dependency__c customset2=new Country_State_Dependency__c();
        customset2.Name='2';
        customset2.Country__c='United States of America';
        customset2.State__c='Alabama';
        customset2.Country_Code__c='US';
        customset2.State_Code__c='AL';
        insert customset2; 
StateCountryController.getStateCountryValues();
}
}