src/objects/POC__c.object
<CustomObject>
    <fields>
        <fullName>Visits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Visits</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POC</label>
    <nameField>
        <label>POC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisitController.cls
public class VisitController{

    private final POC__c poc; 
    public boolean b{get; set{b=false;}}
    public VisitController(ApexPages.StandardController controller) {   
      controller.addfields(new List<String>{'Visits__c'});
      this.poc= (POC__c)controller.getRecord();
      //b=false;
      
    }
    public void increamentor(){
        
        poc.visits__c= poc.visits__c+1;
        System.debug('aaaa====>>>'+poc.visits__c);
        b=true;
        update poc;
    
    }

}